# Generated by Django 3.1.6 on 2023-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230107_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
