# Generated by Django 3.1.6 on 2023-01-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230108_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer'),
        ),
    ]
