# Generated by Django 3.1.6 on 2023-01-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230109_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer'),
        ),
    ]
