# Generated by Django 4.1.5 on 2023-01-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_auto_20230109_1626"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="description", new_name="message",
        ),
        migrations.AddField(
            model_name="message", name="rating", field=models.IntegerField(null=True),
        ),
    ]
