# Generated by Django 4.1.5 on 2023-01-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_rename_description_message_message_message_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="rating",),
    ]
