# Generated by Django 4.1.5 on 2023-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20230117_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
