# Generated by Django 4.1.5 on 2023-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
