# Generated by Django 4.0.6 on 2023-02-19 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_comments_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.FloatField(),
        ),
    ]
