# Generated by Django 4.0.6 on 2023-02-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_comments_created_date_comments_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
        ),
    ]
