# Generated by Django 4.0.6 on 2023-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_shop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='service',
        ),
        migrations.AddField(
            model_name='shop',
            name='service',
            field=models.ManyToManyField(to='shop.service'),
        ),
    ]
