# Generated by Django 4.1.7 on 2023-02-24 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_reviews_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
        ),
    ]
